# Generated by Django 3.1.14 on 2022-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200422_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
