# Generated by Django 3.1.14 on 2022-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
