# Generated by Django 3.1.14 on 2022-11-26 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20221126_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 20, 16, 22, 652497, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
