# Generated by Django 4.1.3 on 2022-11-27 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0015_auto_20221126_2216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 27, 1, 40, 58, 933096, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                (
                    "date_posted",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            11,
                            27,
                            1,
                            40,
                            58,
                            934095,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        choices=[("Feedback", "Feedback"), ("Request", "Request")],
                        default="Feedback",
                        max_length=15,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts",
                "ordering": ["-date_posted"],
            },
        ),
    ]
